/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package avionics;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class camera_logger_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public String fileDir;
    public String filename;
    public boolean enabled;
 
    public camera_logger_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd36f141423ee39e7L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(avionics.camera_logger_t.class))
            return 0L;
 
        classes.add(avionics.camera_logger_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.timestamp); 
 
        __strbuf = new char[this.fileDir.length()]; this.fileDir.getChars(0, this.fileDir.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        __strbuf = new char[this.filename.length()]; this.filename.getChars(0, this.filename.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeByte( this.enabled ? 1 : 0); 
 
    }
 
    public camera_logger_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public camera_logger_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static avionics.camera_logger_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        avionics.camera_logger_t o = new avionics.camera_logger_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.timestamp = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.fileDir = new String(__strbuf);
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.filename = new String(__strbuf);
 
        this.enabled = ins.readByte()!=0;
 
    }
 
    public avionics.camera_logger_t copy()
    {
        avionics.camera_logger_t outobj = new avionics.camera_logger_t();
        outobj.timestamp = this.timestamp;
 
        outobj.fileDir = this.fileDir;
 
        outobj.filename = this.filename;
 
        outobj.enabled = this.enabled;
 
        return outobj;
    }
 
}

