/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package avionics;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class navio_gps_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public double lat;
    public double lon;
    public double alt;
 
    public navio_gps_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x06b2433ce936668dL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(avionics.navio_gps_t.class))
            return 0L;
 
        classes.add(avionics.navio_gps_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeDouble(this.lat); 
 
        outs.writeDouble(this.lon); 
 
        outs.writeDouble(this.alt); 
 
    }
 
    public navio_gps_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public navio_gps_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static avionics.navio_gps_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        avionics.navio_gps_t o = new avionics.navio_gps_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.lat = ins.readDouble();
 
        this.lon = ins.readDouble();
 
        this.alt = ins.readDouble();
 
    }
 
    public avionics.navio_gps_t copy()
    {
        avionics.navio_gps_t outobj = new avionics.navio_gps_t();
        outobj.timestamp = this.timestamp;
 
        outobj.lat = this.lat;
 
        outobj.lon = this.lon;
 
        outobj.alt = this.alt;
 
        return outobj;
    }
 
}

