/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package avionics;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class waypoint_t implements lcm.lcm.LCMEncodable
{
    public double gps[];
 
    public waypoint_t()
    {
        gps = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x65693b45e75564faL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(avionics.waypoint_t.class))
            return 0L;
 
        classes.add(avionics.waypoint_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.gps[a]); 
        }
 
    }
 
    public waypoint_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public waypoint_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static avionics.waypoint_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        avionics.waypoint_t o = new avionics.waypoint_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.gps = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.gps[a] = ins.readDouble();
        }
 
    }
 
    public avionics.waypoint_t copy()
    {
        avionics.waypoint_t outobj = new avionics.waypoint_t();
        outobj.gps = new double[(int) 3];
        System.arraycopy(this.gps, 0, outobj.gps, 0, 3); 
        return outobj;
    }
 
}

