"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pod_data_t(object):
    __slots__ = ["timestamp", "gps", "pod_heading", "wind_data", "pod_wave_off"]

    def __init__(self):
        self.timestamp = 0
        self.gps = [ 0.0 for dim0 in range(2) ]
        self.pod_heading = 0.0
        self.wind_data = [ 0.0 for dim0 in range(2) ]
        self.pod_wave_off = False

    def encode(self):
        buf = BytesIO()
        buf.write(pod_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>2d', *self.gps[:2]))
        buf.write(struct.pack(">d", self.pod_heading))
        buf.write(struct.pack('>2d', *self.wind_data[:2]))
        buf.write(struct.pack(">b", self.pod_wave_off))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pod_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pod_data_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pod_data_t()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.gps = struct.unpack('>2d', buf.read(16))
        self.pod_heading = struct.unpack(">d", buf.read(8))[0]
        self.wind_data = struct.unpack('>2d', buf.read(16))
        self.pod_wave_off = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pod_data_t in parents: return 0
        tmphash = (0x610459f9f6b532ff) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pod_data_t._packed_fingerprint is None:
            pod_data_t._packed_fingerprint = struct.pack(">Q", pod_data_t._get_hash_recursive([]))
        return pod_data_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

