/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package avionics;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class motor_command_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public int L_power;
    public int R_power;
 
    public motor_command_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x33df613dca7879f9L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(avionics.motor_command_t.class))
            return 0L;
 
        classes.add(avionics.motor_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeInt(this.L_power); 
 
        outs.writeInt(this.R_power); 
 
    }
 
    public motor_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public motor_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static avionics.motor_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        avionics.motor_command_t o = new avionics.motor_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.L_power = ins.readInt();
 
        this.R_power = ins.readInt();
 
    }
 
    public avionics.motor_command_t copy()
    {
        avionics.motor_command_t outobj = new avionics.motor_command_t();
        outobj.timestamp = this.timestamp;
 
        outobj.L_power = this.L_power;
 
        outobj.R_power = this.R_power;
 
        return outobj;
    }
 
}

